"""Test ``picasso.io`` — file format read/write round-trips.

Every write goes to a ``tmp_path`` so nothing pollutes ``tests/data/``.
The bundled ``locs`` and ``movie`` fixtures from ``tests/conftest.py``
are reused for round-trip checks against real Picasso data.

Skipped functions (need fixtures we don't have bundled): ``load_ims*``,
``load_nd2``, ``load_stk``, ``load_tif``, ``to_raw``, ``to_raw_combined``.

:author: Rafal Kowalewski, 2026
:copyright: Copyright (c) 2026 Jungmann Lab, MPI of Biochemistry
"""

from __future__ import annotations

import os

import h5py
import numpy as np
import pandas as pd
import pytest
import yaml

from picasso import io, lib

from tests.conftest import PIXELSIZE


# ---------------------------------------------------------------------------
# NoMetadataFileError sanity
# ---------------------------------------------------------------------------


class TestNoMetadataFileError:
    def test_inherits_from_filenotfounderror(self):
        # Many call sites rely on this for graceful fallback.
        assert issubclass(io.NoMetadataFileError, FileNotFoundError)


# ---------------------------------------------------------------------------
# save_info / load_info / _to_dict_walk
# ---------------------------------------------------------------------------


class TestSaveLoadInfo:
    def test_roundtrip_preserves_list_order(self, tmp_path):
        info = [
            {"Width": 64, "Height": 32, "Frames": 100},
            {"Box Size": 7, "Min. Net Gradient": 5000},
        ]
        path = tmp_path / "info.yaml"
        io.save_info(str(path), info)
        loaded = io.load_info(str(path))
        assert loaded == info

    def test_load_info_missing_raises(self, tmp_path):
        # load_info derives the .yaml path from a movie path
        with pytest.raises(io.NoMetadataFileError):
            io.load_info(str(tmp_path / "no_such_movie.raw"))


class TestToDictWalk:
    def test_converts_autodict_recursively(self):
        ad = lib.AutoDict()
        ad["a"]["b"]["c"] = 1
        ad["x"] = 2
        out = io._to_dict_walk(ad)
        assert isinstance(out, dict)
        assert isinstance(out["a"], dict)
        assert isinstance(out["a"]["b"], dict)
        assert out["a"]["b"]["c"] == 1
        assert out["x"] == 2


# ---------------------------------------------------------------------------
# save_raw / load_raw / load_movie
# ---------------------------------------------------------------------------


class TestRawRoundtrip:
    def _synthetic_movie(self):
        rng = np.random.default_rng(0)
        movie = rng.integers(0, 65535, size=(4, 6, 8), dtype=np.uint16)
        info = {
            "Byte Order": "<",
            "Data Type": "uint16",
            "Frames": 4,
            "Height": 6,
            "Width": 8,
            "Generated by": "test_io",
        }
        return movie, info

    def test_save_raw_roundtrip(self, tmp_path):
        movie, info = self._synthetic_movie()
        path = tmp_path / "movie.raw"
        io.save_raw(str(path), movie, [info])
        # save_raw writes both .raw and .yaml
        assert path.exists()
        assert (tmp_path / "movie.yaml").exists()

        loaded, loaded_info = io.load_raw(str(path))
        np.testing.assert_array_equal(np.asarray(loaded), movie)
        assert loaded_info[0]["Frames"] == 4

    def test_load_movie_dispatches_raw(self, tmp_path):
        movie, info = self._synthetic_movie()
        path = tmp_path / "movie.raw"
        io.save_raw(str(path), movie, [info])
        loaded, loaded_info = io.load_movie(str(path))
        np.testing.assert_array_equal(np.asarray(loaded), movie)


# ---------------------------------------------------------------------------
# save_drift / load_drift
# ---------------------------------------------------------------------------


class TestDriftRoundtrip:
    def test_2d_roundtrip(self, tmp_path):
        drift = pd.DataFrame(
            {
                "x": np.linspace(0.0, 1.0, 50),
                "y": np.linspace(0.0, -0.5, 50),
            }
        )
        path = tmp_path / "drift.txt"
        io.save_drift(str(path), drift)
        loaded = io.load_drift(str(path))
        assert list(loaded.columns) == ["x", "y"]
        np.testing.assert_allclose(
            loaded["x"].to_numpy(), drift["x"].to_numpy()
        )
        np.testing.assert_allclose(
            loaded["y"].to_numpy(), drift["y"].to_numpy()
        )

    def test_3d_roundtrip(self, tmp_path):
        drift = pd.DataFrame(
            {
                "x": np.linspace(0.0, 1.0, 30),
                "y": np.linspace(0.0, -0.5, 30),
                "z": np.linspace(-2.0, 2.0, 30),
            }
        )
        path = tmp_path / "drift.txt"
        io.save_drift(str(path), drift)
        loaded = io.load_drift(str(path))
        assert "z" in loaded.columns
        np.testing.assert_allclose(
            loaded["z"].to_numpy(), drift["z"].to_numpy()
        )

    def test_non_txt_extension_raises(self, tmp_path):
        with pytest.raises(ValueError):
            io.load_drift(str(tmp_path / "drift.csv"))


# ---------------------------------------------------------------------------
# save_locs / load_locs / save_datasets — HDF5 round-trips
# ---------------------------------------------------------------------------


class TestSaveLoadLocs:
    def test_roundtrip(self, tmp_path, locs, info):
        path = tmp_path / "locs.hdf5"
        io.save_locs(str(path), locs, info)
        # Side-effect: a .yaml is written alongside the .hdf5
        assert (tmp_path / "locs.yaml").exists()

        loaded, loaded_info = io.load_locs(str(path))
        # Both go through ensure_sanity → row counts may match exactly
        assert len(loaded) == len(locs)
        assert set(loaded.columns) == set(locs.columns)
        # Spot-check numerical content
        np.testing.assert_allclose(
            loaded["x"].to_numpy(), locs["x"].to_numpy()
        )

    def test_csv_extension_raises(self, tmp_path):
        # ThunderSTORM .csv files must go through import_ts, not load_locs
        path = tmp_path / "locs.csv"
        path.write_text("dummy")
        with pytest.raises(ValueError, match="ThunderSTORM"):
            io.load_locs(str(path))


class TestSaveDatasets:
    def test_writes_named_datasets(self, tmp_path):
        path = tmp_path / "datasets.hdf5"
        a = pd.DataFrame({"x": [1.0, 2.0], "y": [3.0, 4.0]})
        b = pd.DataFrame({"x": [10.0], "y": [20.0]})
        info = [{"Width": 32, "Height": 32, "Frames": 1}]
        io.save_datasets(str(path), info, locs=a, picks=b)

        with h5py.File(path, "r") as f:
            assert "locs" in f
            assert "picks" in f
            assert f["locs"].shape == (2,)
            assert f["picks"].shape == (1,)


# ---------------------------------------------------------------------------
# load_calibration
# ---------------------------------------------------------------------------


class TestLoadCalibration:
    def test_returns_dict(self, tmp_path):
        from tests.conftest import CALIB_3D

        path = tmp_path / "calib.yaml"
        with open(path, "w") as f:
            yaml.dump(dict(CALIB_3D), f)
        out = io.load_calibration(str(path))
        assert "X Coefficients" in out
        assert out["Step size in nm"] == 5.0


# ---------------------------------------------------------------------------
# load_picks — write minimal synthetic YAMLs and load them back
# ---------------------------------------------------------------------------


class TestLoadPicks:
    def test_circle_picks(self, tmp_path):
        regions = {
            "Shape": "Circle",
            "Centers": [[5.0, 5.0], [10.0, 10.0]],
            "Diameter (nm)": 130.0,
        }
        path = tmp_path / "picks.yaml"
        with open(path, "w") as f:
            yaml.dump(regions, f)

        picks, shape, size = io.load_picks(str(path), pixelsize=130.0)
        assert shape == "Circle"
        assert picks == [[5.0, 5.0], [10.0, 10.0]]
        assert size == pytest.approx(1.0)

    def test_rectangle_picks(self, tmp_path):
        regions = {
            "Shape": "Rectangle",
            "Center-Axis-Points": [[[0.0, 0.0], [10.0, 0.0]]],
            "Width": 2.0,
        }
        path = tmp_path / "picks.yaml"
        with open(path, "w") as f:
            yaml.dump(regions, f)
        picks, shape, size = io.load_picks(str(path))
        assert shape == "Rectangle"
        assert size == 2.0

    def test_polygon_picks(self, tmp_path):
        regions = {
            "Shape": "Polygon",
            "Vertices": [[[0.0, 0.0], [10.0, 0.0], [10.0, 10.0], [0.0, 0.0]]],
        }
        path = tmp_path / "picks.yaml"
        with open(path, "w") as f:
            yaml.dump(regions, f)
        picks, shape, size = io.load_picks(str(path))
        assert shape == "Polygon"
        assert size is None

    def test_legacy_circle_format(self, tmp_path):
        # Old Picasso versions wrote {Centers, Diameter} without "Shape"
        regions = {
            "Centers": [[5.0, 5.0]],
            "Diameter": 1.5,
        }
        path = tmp_path / "picks.yaml"
        with open(path, "w") as f:
            yaml.dump(regions, f)
        picks, shape, size = io.load_picks(str(path))
        assert shape == "Circle"
        assert size == 1.5

    def test_unrecognized_format_raises(self, tmp_path):
        path = tmp_path / "picks.yaml"
        with open(path, "w") as f:
            yaml.dump({"Foo": "Bar"}, f)
        with pytest.raises(ValueError, match="Unrecognized picks file"):
            io.load_picks(str(path))

    def test_non_yaml_extension_asserts(self, tmp_path):
        path = tmp_path / "picks.txt"
        path.write_text("x")
        with pytest.raises(AssertionError):
            io.load_picks(str(path))


# ---------------------------------------------------------------------------
# Exporters — sanity-check that files are written with expected headers
# ---------------------------------------------------------------------------


class TestExporters:
    def _toy_locs(self, with_z: bool = False) -> pd.DataFrame:
        n = 3
        d = {
            "frame": np.arange(n, dtype=int),
            "x": np.array([1.0, 2.0, 3.0], dtype=np.float32),
            "y": np.array([4.0, 5.0, 6.0], dtype=np.float32),
            "sx": np.array([1.0, 1.0, 1.0], dtype=np.float32),
            "sy": np.array([1.0, 1.0, 1.0], dtype=np.float32),
            "photons": np.array([1000.0, 2000.0, 3000.0], dtype=np.float32),
            "bg": np.array([10.0, 10.0, 10.0], dtype=np.float32),
            "lpx": np.array([0.05, 0.05, 0.05], dtype=np.float32),
            "lpy": np.array([0.05, 0.05, 0.05], dtype=np.float32),
        }
        if with_z:
            d["z"] = np.array([10.0, 20.0, 30.0], dtype=np.float32)
        return pd.DataFrame(d)

    def test_export_txt_imagej(self, tmp_path):
        path = tmp_path / "imagej.txt"
        locs = self._toy_locs()
        io.export_txt_imagej(str(path), locs)
        assert path.exists()
        content = path.read_text()
        # 3 lines, each with frame + x + y separated by 3 spaces
        assert content.count("\n") == 3

    def test_export_txt_nis(self, tmp_path):
        path = tmp_path / "nis.txt"
        locs = self._toy_locs()
        info = [{"Pixelsize": PIXELSIZE}]
        io.export_txt_nis(str(path), locs, info)
        # First line is the NIS header
        with open(path, "rb") as f:
            header = f.readline()
        assert header.startswith(b"X\tY\t")

    def test_export_txt_nis_with_z(self, tmp_path):
        path = tmp_path / "nis_z.txt"
        locs = self._toy_locs(with_z=True)
        info = [{"Pixelsize": PIXELSIZE}]
        io.export_txt_nis(str(path), locs, info)
        with open(path, "rb") as f:
            header = f.readline()
        # 3D header includes Z column
        assert b"\tZ\t" in header

    def test_export_xyz_chimera_with_z(self, tmp_path):
        path = tmp_path / "chimera.xyz"
        locs = self._toy_locs(with_z=True)
        info = [{"Pixelsize": PIXELSIZE}]
        io.export_xyz_chimera(str(path), locs, info)
        assert path.exists()
        with open(path, "rb") as f:
            first = f.readline()
        assert first.startswith(b"Molecule export")

    def test_export_xyz_chimera_warns_without_z(self, tmp_path):
        path = tmp_path / "chimera.xyz"
        locs = self._toy_locs(with_z=False)
        info = [{"Pixelsize": PIXELSIZE}]
        with pytest.warns(UserWarning, match="No z coordinate"):
            io.export_xyz_chimera(str(path), locs, info)

    def test_export_3d_visp(self, tmp_path):
        path = tmp_path / "out.3d"
        locs = self._toy_locs(with_z=True)
        info = [{"Pixelsize": PIXELSIZE}]
        io.export_3d_visp(str(path), locs, info)
        assert path.exists()
        # Must contain at least one row of data
        assert os.path.getsize(path) > 0


# ---------------------------------------------------------------------------
# ThunderSTORM round-trip
# ---------------------------------------------------------------------------


class TestThunderstormRoundtrip:
    def test_export_import_2d(self, tmp_path):
        locs = pd.DataFrame(
            {
                "frame": np.array([0, 1, 2], dtype=np.uint32),
                "x": np.array([5.0, 10.0, 15.0], dtype=np.float32),
                "y": np.array([5.0, 10.0, 15.0], dtype=np.float32),
                "sx": np.array([1.0, 1.0, 1.0], dtype=np.float32),
                "sy": np.array([1.0, 1.0, 1.0], dtype=np.float32),
                "photons": np.array(
                    [1000.0, 2000.0, 3000.0], dtype=np.float32
                ),
                "bg": np.array([10.0, 10.0, 10.0], dtype=np.float32),
                "lpx": np.array([0.05, 0.05, 0.05], dtype=np.float32),
                "lpy": np.array([0.05, 0.05, 0.05], dtype=np.float32),
            }
        )
        info = [
            {"Pixelsize": PIXELSIZE, "Width": 64, "Height": 64, "Frames": 3}
        ]
        ts_path = tmp_path / "ts.csv"
        io.export_thunderstorm(str(ts_path), locs, info)

        # import_ts also writes a sibling _locs.hdf5 — the round-trip we
        # care about here is the in-memory DataFrame.
        out_locs, out_info = io.import_ts(str(ts_path), pixelsize=PIXELSIZE)
        # x/y conversion: nm → pixels via /pixelsize, should match input
        np.testing.assert_allclose(
            out_locs["x"].to_numpy(), locs["x"].to_numpy(), atol=1e-3
        )
        np.testing.assert_allclose(
            out_locs["y"].to_numpy(), locs["y"].to_numpy(), atol=1e-3
        )
        # Frame count is preserved (frames re-zeroed by import_ts)
        assert out_info[0]["Frames"] == 3
