"""Test ``picasso.io`` — file format read/write round-trips.

Every write goes to a ``tmp_path`` so nothing pollutes ``tests/data/``.
The bundled ``locs`` and ``movie`` fixtures from ``tests/conftest.py``
are reused for round-trip checks against real Picasso data.

TIFF loading (``load_tif`` / ``TiffMap`` / ``TiffMultiMap`` / ``to_raw``)
is covered with synthetic ``tifffile``-written stacks generated per test.

Skipped functions (need fixtures we don't have bundled): ``load_ims*``,
``load_nd2``, ``load_stk``.

:author: Rafal Kowalewski, 2026
:copyright: Copyright (c) 2026 Jungmann Lab, MPI of Biochemistry
"""

from __future__ import annotations

import os
import json

import h5py
import numpy as np
import pandas as pd
import pytest
import tifffile
import yaml

from picasso import io, lib

from tests.conftest import PIXELSIZE


# ---------------------------------------------------------------------------
# NoMetadataFileError sanity
# ---------------------------------------------------------------------------


class TestNoMetadataFileError:
    def test_inherits_from_filenotfounderror(self):
        # Many call sites rely on this for graceful fallback.
        assert issubclass(io.NoMetadataFileError, FileNotFoundError)


# ---------------------------------------------------------------------------
# save_info / load_info / _to_dict_walk
# ---------------------------------------------------------------------------


class TestSaveLoadInfo:
    def test_roundtrip_preserves_list_order(self, tmp_path):
        info = [
            {"Width": 64, "Height": 32, "Frames": 100},
            {"Box Size": 7, "Min. Net Gradient": 5000},
        ]
        path = tmp_path / "info.yaml"
        io.save_info(str(path), info)
        loaded = io.load_info(str(path))
        assert loaded == info

    def test_load_info_missing_raises(self, tmp_path):
        # load_info derives the .yaml path from a movie path
        with pytest.raises(io.NoMetadataFileError):
            io.load_info(str(tmp_path / "no_such_movie.raw"))


class TestToDictWalk:
    def test_converts_autodict_recursively(self):
        ad = lib.AutoDict()
        ad["a"]["b"]["c"] = 1
        ad["x"] = 2
        out = io._to_dict_walk(ad)
        assert isinstance(out, dict)
        assert isinstance(out["a"], dict)
        assert isinstance(out["a"]["b"], dict)
        assert out["a"]["b"]["c"] == 1
        assert out["x"] == 2


# ---------------------------------------------------------------------------
# save_raw / load_raw / load_movie
# ---------------------------------------------------------------------------


class TestRawRoundtrip:
    def _synthetic_movie(self):
        rng = np.random.default_rng(0)
        movie = rng.integers(0, 65535, size=(4, 6, 8), dtype=np.uint16)
        info = {
            "Byte Order": "<",
            "Data Type": "uint16",
            "Frames": 4,
            "Height": 6,
            "Width": 8,
            "Generated by": "test_io",
        }
        return movie, info

    def test_save_raw_roundtrip(self, tmp_path):
        movie, info = self._synthetic_movie()
        path = tmp_path / "movie.raw"
        io.save_raw(str(path), movie, [info])
        # save_raw writes both .raw and .yaml
        assert path.exists()
        assert (tmp_path / "movie.yaml").exists()

        loaded, loaded_info = io.load_raw(str(path))
        np.testing.assert_array_equal(np.asarray(loaded), movie)
        assert loaded_info[0]["Frames"] == 4

    def test_load_movie_dispatches_raw(self, tmp_path):
        movie, info = self._synthetic_movie()
        path = tmp_path / "movie.raw"
        io.save_raw(str(path), movie, [info])
        loaded, loaded_info = io.load_movie(str(path))
        np.testing.assert_array_equal(np.asarray(loaded), movie)


# ---------------------------------------------------------------------------
# save_drift / load_drift
# ---------------------------------------------------------------------------


class TestDriftRoundtrip:
    def test_2d_roundtrip(self, tmp_path):
        drift = pd.DataFrame(
            {
                "x": np.linspace(0.0, 1.0, 50),
                "y": np.linspace(0.0, -0.5, 50),
            }
        )
        path = tmp_path / "drift.txt"
        io.save_drift(str(path), drift)
        loaded = io.load_drift(str(path))
        assert list(loaded.columns) == ["x", "y"]
        np.testing.assert_allclose(
            loaded["x"].to_numpy(), drift["x"].to_numpy()
        )
        np.testing.assert_allclose(
            loaded["y"].to_numpy(), drift["y"].to_numpy()
        )

    def test_3d_roundtrip(self, tmp_path):
        drift = pd.DataFrame(
            {
                "x": np.linspace(0.0, 1.0, 30),
                "y": np.linspace(0.0, -0.5, 30),
                "z": np.linspace(-2.0, 2.0, 30),
            }
        )
        path = tmp_path / "drift.txt"
        io.save_drift(str(path), drift)
        loaded = io.load_drift(str(path))
        assert "z" in loaded.columns
        np.testing.assert_allclose(
            loaded["z"].to_numpy(), drift["z"].to_numpy()
        )

    def test_non_txt_extension_raises(self, tmp_path):
        with pytest.raises(ValueError):
            io.load_drift(str(tmp_path / "drift.csv"))


# ---------------------------------------------------------------------------
# save_locs / load_locs / save_datasets — HDF5 round-trips
# ---------------------------------------------------------------------------


class TestSaveLoadLocs:
    def test_roundtrip(self, tmp_path, locs, info):
        path = tmp_path / "locs.hdf5"
        io.save_locs(str(path), locs, info)
        # Side-effect: a .yaml is written alongside the .hdf5
        assert (tmp_path / "locs.yaml").exists()

        loaded, loaded_info = io.load_locs(str(path))
        # Both go through ensure_sanity → row counts may match exactly
        assert len(loaded) == len(locs)
        assert set(loaded.columns) == set(locs.columns)
        # Spot-check numerical content
        np.testing.assert_allclose(
            loaded["x"].to_numpy(), locs["x"].to_numpy()
        )

    def test_csv_extension_raises(self, tmp_path):
        # ThunderSTORM .csv files must go through import_ts, not load_locs
        path = tmp_path / "locs.csv"
        path.write_text("dummy")
        with pytest.raises(ValueError, match="ThunderSTORM"):
            io.load_locs(str(path))


class TestSaveDatasets:
    def test_writes_named_datasets(self, tmp_path):
        path = tmp_path / "datasets.hdf5"
        a = pd.DataFrame({"x": [1.0, 2.0], "y": [3.0, 4.0]})
        b = pd.DataFrame({"x": [10.0], "y": [20.0]})
        info = [{"Width": 32, "Height": 32, "Frames": 1}]
        io.save_datasets(str(path), info, locs=a, picks=b)

        with h5py.File(path, "r") as f:
            assert "locs" in f
            assert "picks" in f
            assert f["locs"].shape == (2,)
            assert f["picks"].shape == (1,)


# ---------------------------------------------------------------------------
# load_calibration
# ---------------------------------------------------------------------------


class TestLoadCalibration:
    def test_returns_dict(self, tmp_path):
        from tests.conftest import CALIB_3D

        path = tmp_path / "calib.yaml"
        with open(path, "w") as f:
            yaml.dump(dict(CALIB_3D), f)
        out = io.load_calibration(str(path))
        assert "X Coefficients" in out
        assert out["Step size in nm"] == 5.0


# ---------------------------------------------------------------------------
# load_picks — write minimal synthetic YAMLs and load them back
# ---------------------------------------------------------------------------


class TestLoadPicks:
    def test_circle_picks(self, tmp_path):
        regions = {
            "Shape": "Circle",
            "Centers": [[5.0, 5.0], [10.0, 10.0]],
            "Diameter (nm)": 130.0,
        }
        path = tmp_path / "picks.yaml"
        with open(path, "w") as f:
            yaml.dump(regions, f)

        picks, shape, size = io.load_picks(str(path), pixelsize=130.0)
        assert shape == "Circle"
        assert picks == [[5.0, 5.0], [10.0, 10.0]]
        assert size == pytest.approx(1.0)

    def test_rectangle_picks(self, tmp_path):
        regions = {
            "Shape": "Rectangle",
            "Center-Axis-Points": [[[0.0, 0.0], [10.0, 0.0]]],
            "Width": 2.0,
        }
        path = tmp_path / "picks.yaml"
        with open(path, "w") as f:
            yaml.dump(regions, f)
        picks, shape, size = io.load_picks(str(path))
        assert shape == "Rectangle"
        assert size == 2.0

    def test_polygon_picks(self, tmp_path):
        regions = {
            "Shape": "Polygon",
            "Vertices": [[[0.0, 0.0], [10.0, 0.0], [10.0, 10.0], [0.0, 0.0]]],
        }
        path = tmp_path / "picks.yaml"
        with open(path, "w") as f:
            yaml.dump(regions, f)
        picks, shape, size = io.load_picks(str(path))
        assert shape == "Polygon"
        assert size is None

    def test_legacy_circle_format(self, tmp_path):
        # Old Picasso versions wrote {Centers, Diameter} without "Shape"
        regions = {
            "Centers": [[5.0, 5.0]],
            "Diameter": 1.5,
        }
        path = tmp_path / "picks.yaml"
        with open(path, "w") as f:
            yaml.dump(regions, f)
        picks, shape, size = io.load_picks(str(path))
        assert shape == "Circle"
        assert size == 1.5

    def test_unrecognized_format_raises(self, tmp_path):
        path = tmp_path / "picks.yaml"
        with open(path, "w") as f:
            yaml.dump({"Foo": "Bar"}, f)
        with pytest.raises(ValueError, match="Unrecognized picks file"):
            io.load_picks(str(path))

    def test_non_yaml_extension_asserts(self, tmp_path):
        path = tmp_path / "picks.txt"
        path.write_text("x")
        with pytest.raises(AssertionError):
            io.load_picks(str(path))


# ---------------------------------------------------------------------------
# Exporters — sanity-check that files are written with expected headers
# ---------------------------------------------------------------------------


class TestExporters:
    def _toy_locs(self, with_z: bool = False) -> pd.DataFrame:
        n = 3
        d = {
            "frame": np.arange(n, dtype=int),
            "x": np.array([1.0, 2.0, 3.0], dtype=np.float32),
            "y": np.array([4.0, 5.0, 6.0], dtype=np.float32),
            "sx": np.array([1.0, 1.0, 1.0], dtype=np.float32),
            "sy": np.array([1.0, 1.0, 1.0], dtype=np.float32),
            "photons": np.array([1000.0, 2000.0, 3000.0], dtype=np.float32),
            "bg": np.array([10.0, 10.0, 10.0], dtype=np.float32),
            "lpx": np.array([0.05, 0.05, 0.05], dtype=np.float32),
            "lpy": np.array([0.05, 0.05, 0.05], dtype=np.float32),
        }
        if with_z:
            d["z"] = np.array([10.0, 20.0, 30.0], dtype=np.float32)
        return pd.DataFrame(d)

    def test_export_txt_imagej(self, tmp_path):
        path = tmp_path / "imagej.txt"
        locs = self._toy_locs()
        io.export_txt_imagej(str(path), locs)
        assert path.exists()
        content = path.read_text()
        # 3 lines, each with frame + x + y separated by 3 spaces
        assert content.count("\n") == 3

    def test_export_txt_nis(self, tmp_path):
        path = tmp_path / "nis.txt"
        locs = self._toy_locs()
        info = [{"Pixelsize": PIXELSIZE}]
        io.export_txt_nis(str(path), locs, info)
        # First line is the NIS header
        with open(path, "rb") as f:
            header = f.readline()
        assert header.startswith(b"X\tY\t")

    def test_export_txt_nis_with_z(self, tmp_path):
        path = tmp_path / "nis_z.txt"
        locs = self._toy_locs(with_z=True)
        info = [{"Pixelsize": PIXELSIZE}]
        io.export_txt_nis(str(path), locs, info)
        with open(path, "rb") as f:
            header = f.readline()
        # 3D header includes Z column
        assert b"\tZ\t" in header

    def test_export_xyz_chimera_with_z(self, tmp_path):
        path = tmp_path / "chimera.xyz"
        locs = self._toy_locs(with_z=True)
        info = [{"Pixelsize": PIXELSIZE}]
        io.export_xyz_chimera(str(path), locs, info)
        assert path.exists()
        with open(path, "rb") as f:
            first = f.readline()
        assert first.startswith(b"Molecule export")

    def test_export_xyz_chimera_warns_without_z(self, tmp_path):
        path = tmp_path / "chimera.xyz"
        locs = self._toy_locs(with_z=False)
        info = [{"Pixelsize": PIXELSIZE}]
        with pytest.warns(UserWarning, match="No z coordinate"):
            io.export_xyz_chimera(str(path), locs, info)

    def test_export_3d_visp(self, tmp_path):
        path = tmp_path / "out.3d"
        locs = self._toy_locs(with_z=True)
        info = [{"Pixelsize": PIXELSIZE}]
        io.export_3d_visp(str(path), locs, info)
        assert path.exists()
        # Must contain at least one row of data
        assert os.path.getsize(path) > 0


# ---------------------------------------------------------------------------
# ThunderSTORM round-trip
# ---------------------------------------------------------------------------


class TestThunderstormRoundtrip:
    def test_export_import_2d(self, tmp_path):
        locs = pd.DataFrame(
            {
                "frame": np.array([0, 1, 2], dtype=np.uint32),
                "x": np.array([5.0, 10.0, 15.0], dtype=np.float32),
                "y": np.array([5.0, 10.0, 15.0], dtype=np.float32),
                "sx": np.array([1.0, 1.0, 1.0], dtype=np.float32),
                "sy": np.array([1.0, 1.0, 1.0], dtype=np.float32),
                "photons": np.array(
                    [1000.0, 2000.0, 3000.0], dtype=np.float32
                ),
                "bg": np.array([10.0, 10.0, 10.0], dtype=np.float32),
                "lpx": np.array([0.05, 0.05, 0.05], dtype=np.float32),
                "lpy": np.array([0.05, 0.05, 0.05], dtype=np.float32),
            }
        )
        info = [
            {"Pixelsize": PIXELSIZE, "Width": 64, "Height": 64, "Frames": 3}
        ]
        ts_path = tmp_path / "ts.csv"
        io.export_thunderstorm(str(ts_path), locs, info)

        # import_ts also writes a sibling _locs.hdf5 — the round-trip we
        # care about here is the in-memory DataFrame.
        out_locs, out_info = io.import_ts(str(ts_path), pixelsize=PIXELSIZE)
        # x/y conversion: nm → pixels via /pixelsize, should match input
        np.testing.assert_allclose(
            out_locs["x"].to_numpy(), locs["x"].to_numpy(), atol=1e-3
        )
        np.testing.assert_allclose(
            out_locs["y"].to_numpy(), locs["y"].to_numpy(), atol=1e-3
        )
        # Frame count is preserved (frames re-zeroed by import_ts)
        assert out_info[0]["Frames"] == 3


# ---------------------------------------------------------------------------
# TIFF loading — TiffMap / TiffMultiMap / load_tif / to_raw
#
# Picasso reads TIFFs via ``tifffile`` (see picasso.io.TiffMap). Real
# microscopy movies store one IFD per frame, so the fixtures here are
# written frame-by-frame (a single 3-D array would be collapsed into one
# volumetric page by tifffile and would not represent a real movie).
# ---------------------------------------------------------------------------


def _write_tif_stack(
    path,
    data,
    byteorder=None,
    bigtiff=False,
    compression=None,
    mm_metadata=None,
):
    """Write ``data`` (frames, H, W) as a multi-page TIFF, one IFD per
    frame. Optionally big-endian, BigTIFF, compressed, or with a
    MicroManager metadata tag (51123) on the first page."""
    with tifffile.TiffWriter(
        str(path), byteorder=byteorder, bigtiff=bigtiff, ome=False
    ) as tw:
        for i, frame in enumerate(data):
            kw = {}
            if i == 0 and mm_metadata is not None:
                kw["extratags"] = [
                    (51123, "s", 0, json.dumps(mm_metadata), True)
                ]
            tw.write(
                frame,
                photometric="minisblack",
                compression=compression,
                contiguous=(compression is None),
                **kw,
            )


class TestTiffLoading:
    def test_load_tif_basic_shape_dtype_frames(self, tmp_path):
        rng = np.random.default_rng(0)
        data = rng.integers(0, 60000, size=(7, 32, 48), dtype="<u2")
        path = tmp_path / "plain.tif"
        _write_tif_stack(path, data)

        movie, info = io.load_tif(str(path))
        try:
            assert movie.shape == (7, 32, 48)
            assert movie.dtype == np.dtype("<u2")
            assert movie.n_frames == 7
            assert len(movie) == 7
            assert info[0]["Height"] == 32
            assert info[0]["Width"] == 48
            assert info[0]["Frames"] == 7
            assert info[0]["Data Type"] == "uint16"
        finally:
            movie.close()

    def test_frame_slice_and_iter_access(self, tmp_path):
        rng = np.random.default_rng(1)
        data = rng.integers(0, 60000, size=(6, 16, 20), dtype="<u2")
        path = tmp_path / "access.tif"
        _write_tif_stack(path, data)

        movie, _ = io.load_tif(str(path))
        try:
            np.testing.assert_array_equal(movie[3], data[3])
            np.testing.assert_array_equal(np.array(movie[2:5]), data[2:5])
            np.testing.assert_array_equal(movie[...], data)
            np.testing.assert_array_equal(np.array(list(movie)), data)
            # Region indexing
            np.testing.assert_array_equal(
                movie[4, 5:10, 3:7], data[4, 5:10, 3:7]
            )
            # Single frames are little-endian 2-D arrays
            assert movie[0].dtype == np.dtype("<u2")
            assert movie[0].shape == (16, 20)
        finally:
            movie.close()

    def test_big_endian_normalized_to_little_endian(self, tmp_path):
        rng = np.random.default_rng(2)
        data = rng.integers(0, 60000, size=(4, 16, 20), dtype="<u2")
        path = tmp_path / "be.tif"
        _write_tif_stack(path, data.astype(">u2"), byteorder=">")

        movie, info = io.load_tif(str(path))
        try:
            # Values must be preserved despite byte-order conversion
            np.testing.assert_array_equal(np.array(list(movie)), data)
            assert movie.dtype == np.dtype("<u2")
            assert movie[1].dtype.byteorder in ("<", "=")
            # info preserves the file's native byte order
            assert info[0]["Byte Order"] == ">"
        finally:
            movie.close()

    def test_bigtiff(self, tmp_path):
        rng = np.random.default_rng(3)
        data = rng.integers(0, 255, size=(3, 10, 12), dtype="<u2")
        path = tmp_path / "big.tif"
        _write_tif_stack(path, data, bigtiff=True)

        movie, _ = io.load_tif(str(path))
        try:
            assert movie.n_frames == 3
            np.testing.assert_array_equal(np.array(list(movie)), data)
        finally:
            movie.close()

    def test_compressed_falls_back_to_decoder(self, tmp_path):
        rng = np.random.default_rng(4)
        data = rng.integers(0, 1000, size=(5, 16, 16), dtype="<u2")
        path = tmp_path / "zip.tif"
        _write_tif_stack(path, data, compression="zlib")

        movie, _ = io.load_tif(str(path))
        try:
            # Compressed pages are not contiguous → fast path disabled
            assert movie.maps[0]._uncompressed is False
            np.testing.assert_array_equal(np.array(list(movie)), data)
            np.testing.assert_array_equal(movie[2], data[2])
        finally:
            movie.close()

    def test_multifile_ome_concatenation(self, tmp_path):
        rng = np.random.default_rng(5)
        parts = [
            rng.integers(0, 500, size=(3, 8, 8), dtype="<u2") for _ in range(3)
        ]
        base = tmp_path / "mov"
        _write_tif_stack(str(base) + ".ome.tif", parts[0])
        _write_tif_stack(str(base) + "_1.ome.tif", parts[1])
        _write_tif_stack(str(base) + "_2.ome.tif", parts[2])

        movie, info = io.load_tif(str(base) + ".ome.tif")
        try:
            expected = np.concatenate(parts, axis=0)
            assert movie.n_frames == 9
            assert info[0]["Frames"] == 9
            np.testing.assert_array_equal(np.array(list(movie)), expected)
            # Frame routing across files
            np.testing.assert_array_equal(movie[7], expected[7])
        finally:
            movie.close()

    def test_micromanager_metadata_flattened(self, tmp_path):
        rng = np.random.default_rng(6)
        data = rng.integers(0, 500, size=(2, 8, 8), dtype="<u2")
        path = tmp_path / "mm.tif"
        mm = {
            "Camera": "TestCam",
            # MM 2.0 nests values under PropVal — must be flattened
            "TestCam-Gain": {"PropName": "Gain", "PropVal": "300"},
            "scopeDataKeys": {"ignored": 1},
        }
        _write_tif_stack(path, data, mm_metadata=mm)

        movie, info = io.load_tif(str(path))
        try:
            meta = info[0]
            assert meta["Camera"] == "TestCam"
            mm_meta = meta["Micro-Manager Metadata"]
            assert mm_meta["TestCam-Gain"] == "300"
            assert mm_meta["Camera"] == "TestCam"
            assert "scopeDataKeys" not in mm_meta
            # The comments key is always present for parity with old reader
            assert "Micro-Manager Acquisition Comments" in meta
        finally:
            movie.close()

    def test_non_mm_tiff_has_no_camera_key(self, tmp_path):
        rng = np.random.default_rng(7)
        data = rng.integers(0, 500, size=(2, 8, 8), dtype="<u2")
        path = tmp_path / "plain2.tif"
        _write_tif_stack(path, data)

        movie, info = io.load_tif(str(path))
        try:
            assert "Camera" not in info[0]
            assert "Micro-Manager Metadata" not in info[0]
        finally:
            movie.close()

    def test_load_movie_dispatches_tif(self, tmp_path):
        rng = np.random.default_rng(8)
        data = rng.integers(0, 60000, size=(4, 12, 10), dtype="<u2")
        path = tmp_path / "dispatch.tif"
        _write_tif_stack(path, data)

        movie, _ = io.load_movie(str(path))
        try:
            assert isinstance(movie, io.AbstractPicassoMovie)
            np.testing.assert_array_equal(np.array(list(movie)), data)
        finally:
            movie.close()

    def test_to_raw_roundtrip(self, tmp_path):
        rng = np.random.default_rng(9)
        data = rng.integers(0, 60000, size=(4, 8, 8), dtype="<u2")
        base = tmp_path / "grp"
        _write_tif_stack(str(base) + ".ome.tif", data[:2])
        _write_tif_stack(str(base) + "_1.ome.tif", data[2:])

        io.to_raw(str(base) + "*.ome.tif", verbose=False)

        raw = np.fromfile(str(base) + ".ome.raw", dtype="<u2").reshape(4, 8, 8)
        np.testing.assert_array_equal(raw, data)
        meta = io.load_info(str(base) + ".ome.yaml")
        assert meta[0]["Frames"] == 4
        assert meta[0]["Byte Order"] == "<"

    @pytest.mark.parametrize("ext", [".btf", ".tf8", ".tf2"])
    def test_bigtiff_extensions_load_via_load_movie(self, tmp_path, ext):
        rng = np.random.default_rng(10)
        data = rng.integers(0, 60000, size=(4, 12, 10), dtype="<u2")
        path = tmp_path / ("movie" + ext)
        _write_tif_stack(path, data, bigtiff=True)

        movie, info = io.load_movie(str(path))
        try:
            assert isinstance(movie, io.AbstractPicassoMovie)
            assert movie.shape == (4, 12, 10)
            assert movie.n_frames == 4
            assert info[0]["Frames"] == 4
            np.testing.assert_array_equal(np.array(list(movie)), data)
        finally:
            movie.close()


# ---------------------------------------------------------------------------
# Movie extension dispatch — MOVIE_EXTENSIONS / TIFF_EXTENSIONS / load_movie
#
# Note: tifffile cannot WRITE .lsm, so LSM read-correctness cannot be
# unit-tested without a real sample file. We only verify that a .lsm path is
# dispatched to load_tif; reading a real .lsm should be validated manually.
# ---------------------------------------------------------------------------


class TestMovieExtensions:
    def test_constants_contents(self):
        # TIFF family routed to the tifffile-backed reader
        for ext in (".tif", ".tiff", ".btf", ".tf8", ".tf2", ".lsm"):
            assert ext in io.TIFF_EXTENSIONS
        # MOVIE_EXTENSIONS is the full set incl. the dedicated-loader formats
        assert set(io.TIFF_EXTENSIONS) <= set(io.MOVIE_EXTENSIONS)
        for ext in (".raw", ".ims", ".nd2", ".stk"):
            assert ext in io.MOVIE_EXTENSIONS

    def test_unsupported_extension_raises(self, tmp_path):
        path = tmp_path / "movie.foobar"
        path.write_bytes(b"not a movie")
        with pytest.raises(ValueError, match="Unsupported movie format"):
            io.load_movie(str(path))

    @pytest.mark.parametrize("ext", [".tif", ".tiff", ".btf", ".tf8", ".lsm"])
    def test_tiff_family_dispatches_to_load_tif(
        self, tmp_path, monkeypatch, ext
    ):
        # Route every TIFF-family extension through load_tif without needing
        # a real file for each (esp. .lsm, which tifffile cannot write).
        called = {}

        def fake_load_tif(path, progress=None):
            called["path"] = path
            return "MOVIE", [{}]

        monkeypatch.setattr(io, "load_tif", fake_load_tif)
        path = tmp_path / ("movie" + ext)
        movie, info = io.load_movie(str(path))
        assert movie == "MOVIE"
        assert called["path"] == str(path)
